export const AdidasProducts = [
     {
        "id": 1,
        "name": "Adidas Nizza X Disney",
        "brand": "ADIDAS",
        "gender": "KIDS",
        "category": "CASUAL",
        "price": '$55',
        "is_in_inventory": true,
        "items_left": 6,
        "imageURL": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/ef901c7aeac042578eceab9d0159196c_9366/Nizza_x_Disney_Sport_Goofy_Shoes_White_FW0651_01_standard.jpg",
        "slug": "nizza-x-disney",
        "featured" : 0
      },
      {
        "id": 2,
        "name": "Adidas X_PLR",
        "brand": "ADIDAS",
        "gender": "KIDS",
        "category": "CASUAL",
        "price": '$65',
        "is_in_inventory": true,
        "items_left": 5,
        "imageURL": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/a36518227134495da766ab9d01772fa2_9366/X_PLR_Shoes_Red_FY9063_01_standard.jpg",
        "slug": "x_plr",
        "featured" : 1
      },
      {
        "id": 3,
        "name": "Adidas Stan Smith",
        "brand": "ADIDAS",
        "gender": "KIDS",
        "category": "CASUAL",
        "price": '$55',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/d0720712d81e42b1b30fa80800826447_9366/Stan_Smith_Shoes_White_M20607_M20607_01_standard.jpg",
        "slug": "stan-smith",
        "featured" : 0
      },
      {
        "id": 4,
        "name": "Adidas NMD_R1",
        "brand": "ADIDAS",
        "gender": "KIDS",
        "category": "RUNNING",
        "price": '$120',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/99ca762cb9054caf82fbabc500fd146e_9366/NMD_R1_Shoes_Blue_FY9392_01_standard.jpg",
        "slug": "nmd_r1",
        "featured" : 0
      },
      {
        "id": 5,
        "name": "Adidas NMD_R1 Flash Red",
        "brand": "ADIDAS",
        "gender": "WOMEN",
        "category": "CASUAL",
        "price": '$140',
        "is_in_inventory": true,
        "items_left": 5,
        "imageURL": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/90f85768e3894aeaab67aba0014a3379_9366/NMD_R1_Shoes_Red_FY9389_01_standard.jpg",
        "slug": "nmd_r1-flash-red",
        "featured" : 0
      },
      {
        "id": 6,
        "name": "Adidas Superstar",
        "brand": "ADIDAS",
        "gender": "WOMEN",
        "category": "CASUAL",
        "price": '$90',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://assets.adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/12365dbc7c424288b7cdab4900dc7099_9366/Superstar_Shoes_White_FW3553_FW3553_01_standard.jpg",
        "slug": "superstar",
        "featured" : 0
      },
     
]