export const PumaProducts = [
    {
        "id": 1,
        "name": "Puma Roma",
        "brand": "Puma",
        "gender": "male",
        "category": "CASUAL",
        "price": '$60',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.runrepeat.com/i/puma/25113/puma-roma-basic-baskets-mode-pour-homme-white-teamregalred-white-black-13-uk-homme-white-black-3069-600.jpg",
        "slug": "sk80-low",
        "featured" : 0
      },
      {
        "id": 2,
        "name": "PUMA Pacer Future",
        "brand": "Puma",
        "gender": "women",
        "category": "CASUAL",
        "price": '$60',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.runrepeat.com/i/puma/37428/puma-women-s-pacer-future-sneaker-eggnog-white-rose-gold-8-5-eggnog-puma-white-rose-gold-216d-600.jpg",
        "slug": "sk80-low",
        "featured" : 0
      },
      {
        "id": 3,
        "name": "PUMA Prowl Slip-On",
        "brand": "Puma",
        "gender": "women",
        "category": "CASUAL",
        "price": '$60',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.runrepeat.com/i/puma/36735/puma-prowl-slip-on-lotus-rose-gold-lotus-rose-gold-0b38-380.jpg",
        "slug": "sk80-low",
        "featured" : 0
      },
      {
        "id": 4,
        "name": "PUMA Anzarun",
        "brand": "Puma",
        "gender": "male",
        "category": "CASUAL",
        "price": '$60',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.runrepeat.com/i/puma/35116/puma-anzarun-peacoat-high-risk-red-ff22-600.jpg",
        "slug": "sk80-low",
        "featured" : 0
      },
      {
        "id": 5,
        "name": "PUMA Easy Rider",
        "brand": "Puma",
        "gender": "male",
        "category": "CASUAL",
        "price": '$60',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.runrepeat.com/i/puma/25068/puma-mens-easy-rider-ii-techno-381027-02-size-9-black-black-7952-600.jpg",
        "slug": "sk80-low",
        "featured" : 0
      },
      {
        "id": 6,
        "name": "PUMA R78",
        "brand": "Puma",
        "gender": "male",
        "category": "CASUAL",
        "price": '$60',
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.runrepeat.com/i/puma/36309/puma-mens-r78-sneaker-black-white-3-women-4-5-men-us-puma-black-puma-white-db30-600.jpg",
        "slug": "sk80-low",
        "featured" : 0
      },

]