export const VarietyProducts = [
     {
        "id": 1,
        "name": "Bridgport Advice",
        "brand": "HUSHPUPPIES",
        "gender": "MEN",
        "category": "FORMAL",
        "price": 30,
        "is_in_inventory": true,
        "items_left": 4,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/BRIDGPORT_ADVICE-BLACK_1_800x800.jpg?v=1576567903",
        "slug": "bridgport-advice",
        "featured" : 1
      },
      {
        "id": 2,
        "name": "Beck",
        "brand": "HUSHPUPPIES",
        "gender": "MEN",
        "category": "FORMAL",
        "price": 80,
        "is_in_inventory": true,
        "items_left": 5,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/Beck-Black_800x800.jpg",
        "slug": "beck",
        "featured" : 0
      },
      {
        "id": 3,
        "name": "Fester",
        "brand": "HUSHPUPPIES",
        "gender": "MEN",
        "category": "FORMAL",
        "price": 70,
        "is_in_inventory": true,
        "items_left": 6,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/fester-Tan_800x800.jpg?v=1575537531",
        "slug": "fester",
        "featured" : 0
      },
      {
        "id": 4,
        "name": "Pixel",
        "brand": "HUSHPUPPIES",
        "gender": "MEN",
        "category": "FORMAL",
        "price": 75,
        "is_in_inventory": true,
        "items_left": 7,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/PIXEL-TAN_800x800.jpg?v=1577420506",
        "slug": "pixel",
        "featured" : 0
      },
      {
        "id": 5,
        "name": "Austin",
        "brand": "HUSHPUPPIES",
        "gender": "MEN",
        "category": "FORMAL",
        "price": 75,
        "is_in_inventory": true,
        "items_left": 2,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/Austin-Coffee_800x800.jpg?v=1574772988",
        "slug": "austin",
        "featured" : 0
      },
      {
        "id": 6,
        "name": "SS-HL-0135",
        "brand": "HUSHPUPPIES",
        "gender": "WOMEN",
        "category": "FORMAL",
        "price": 30,
        "is_in_inventory": true,
        "items_left": 6,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009240000-11-SS-HL-0135-Black_800x800.jpg?v=1572264270",
        "slug": "ss-hl-0135",
        "featured" : 0
      },
      {
        "id": 7,
        "name": "SS-HL-0136",
        "brand": "HUSHPUPPIES",
        "gender": "WOMEN",
        "category": "FORMAL",
        "price": 50,
        "is_in_inventory": true,
        "items_left": 4,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009250000-779-SS-HL-0136-Coffee_800x800.jpg?v=1571900372",
        "slug": "ss-hl-0136",
        "featured" : 0
      },
      {
        "id": 8,
        "name": "SS-HL-0128",
        "brand": "HUSHPUPPIES",
        "gender": "WOMEN",
        "category": "FORMAL",
        "price": 35,
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/000300242-484-SS-HL-0128-Blue_800x800.jpg?v=1583235174",
        "slug": "ss-hl-0128",
        "featured" : 0
      },
      {
        "id": 9,
        "name": "SS-MS-0075",
        "brand": "HUSHPUPPIES",
        "gender": "WOMEN",
        "category": "CASUAL",
        "price": 25,
        "is_in_inventory": true,
        "items_left": 7,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009170000-479-SS-MS-0075-Red_800x800.jpg?v=1570688687",
        "slug": "ss-ms-0075",
        "featured" : 0
      },
       {
        "id": 10,
        "name": "SS-PM-0093",
        "brand": "HUSHPUPPIES",
        "gender": "WOMEN",
        "category": "CASUAL",
        "price": 30,
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/SS-PM-0093_1_800x800.jpg?v=1570601253",
        "slug": "ss-pm-0093",
        "featured" : 0
      },
      {
        "id": 11,
        "name": "Club C Revenge Mens",
        "brand": "Reebok",
        "gender": "MEN",
        "category": "CASUAL",
        "price": 70,
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/7599294868804d78a1b1ab6f01718a5e_9366/Club_C_Revenge_Men's_Shoes_White_FV9877_01_standard.jpg",
        "slug": "club-c-revenge-mens",
        "featured" : 0
      },
      {
        "id": 12,
        "name": "SK80-Low",
        "brand": "Vans",
        "gender": "MEN",
        "category": "CASUAL",
        "price": 60,
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://images.vans.com/is/image/Vans/UUK24I-HERO?$583x583$",
        "slug": "sk80-low",
        "featured" : 0
      },
      {
        "id": 13,
        "name": "Michael Feburary SK8-Hi",
        "brand": "Vans",
        "gender": "MEN",
        "category": "CASUAL",
        "price": 72,
        "is_in_inventory": true,
        "items_left": 3,
        "imageURL": "https://images.vans.com/is/image/Vans/MV122M-HERO?$583x583$",
        "slug": "michael-feburary-sk8-hi",
        "featured" : 0
      }
]